version: "2"

networks:
  geodb:

volumes:
        peer0.operations0.geodb.com:
        peer1.operations0.geodb.com:
        peer2.operations0.geodb.com:
        peer3.operations0.geodb.com:
        peer0.operations1.geodb.com:
        peer1.operations1.geodb.com:
        peer2.operations1.geodb.com:
        peer3.operations1.geodb.com:

services:
  
  peer0.operations0.geodb.com:
    extends:
      file: ../bases/peer-base.yaml
      service: peer
    container_name: peer0.operations0.geodb.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=peer0.operations0.geodb.com
      - CORE_PEER_ADDRESS=peer0.operations0.geodb.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_LOCALMSPID=geodbMSP
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.operations0.geodb.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.operations0.geodb.com:7151 peer2.operations0.geodb.com:7251 peer3.operations0.geodb.com:7351
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/org1/peer0
    volumes:
      - /var/run:/host/var/run
      - ../crypto-config/peerOrganizations/operations0.geodb.com/peers/peer0.operations0.geodb.com:/etc/hyperledger/peer
    # ports:
    #   - 7051:7051
    #   - 7053:7053
    networks:
      - geodb

  peer1.operations0.geodb.com:
    extends:
      file: ../bases/peer-base.yaml
      service: peer
    container_name: peer1.operations0.geodb.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=peer1.operations0.geodb.com
      - CORE_PEER_ADDRESS=peer1.operations0.geodb.com:7151
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7151
      - CORE_PEER_LOCALMSPID=geodbMSP
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.operations0.geodb.com:7151
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.operations0.geodb.com:7051 peer2.operations0.geodb.com:7251 peer3.operations0.geodb.com:7351
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/org1/peer1
    volumes:
      - /var/run:/host/var/run
      - ../crypto-config/peerOrganizations/operations0.geodb.com/peers/peer1.operations0.geodb.com:/etc/hyperledger/peer
    # ports:
    #   - 7151:7151
    #   - 7153:7153
    networks:
      - geodb

  peer2.operations0.geodb.com:
    extends:
      file: ../bases/peer-base.yaml
      service: peer
    container_name: peer2.operations0.geodb.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=peer2.operations0.geodb.com
      - CORE_PEER_ADDRESS=peer2.operations0.geodb.com:7251
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7251
      - CORE_PEER_LOCALMSPID=geodbMSP
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.operations0.geodb.com:7251
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.operations0.geodb.com:7051 peer1.operations0.geodb.com:7151 peer3.operations0.geodb.com:7351
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/org1/peer2
    volumes:
      - /var/run:/host/var/run
      - ../crypto-config/peerOrganizations/operations0.geodb.com/peers/peer2.operations0.geodb.com:/etc/hyperledger/peer
    # ports:
    #   - 7051:7051
    #   - 7053:7053
    networks:
      - geodb 

  peer3.operations0.geodb.com:
    extends:
      file: ../bases/peer-base.yaml
      service: peer
    container_name: peer3.operations0.geodb.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=peer3.operations0.geodb.com
      - CORE_PEER_ADDRESS=peer3.operations0.geodb.com:7351
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7351
      - CORE_PEER_LOCALMSPID=geodbMSP
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer3.operations0.geodb.com:7351
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.operations0.geodb.com:7051 peer1.operations0.geodb.com:7151 peer2.operations0.geodb.com:7251
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/org1/peer2
    volumes:
      - /var/run:/host/var/run
      - ../crypto-config/peerOrganizations/operations0.geodb.com/peers/peer3.operations0.geodb.com:/etc/hyperledger/peer
    # ports:
    #   - 7051:7051
    #   - 7053:7053
    networks:
      - geodb

  clipeer0.operations0.geodb.com:
    extends:
      file: ../bases/cli-base.yaml
      service: cli
    container_name: clipeer0.operations0.geodb.com
    environment:
      - CORE_PEER_ID=clipeer0.operations0.geodb.com
      - CORE_PEER_ADDRESS=peer0.operations0.geodb.com:7051
      - CORE_PEER_LOCALMSPID=geodbMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@operations0.geodb.com/msp
      # - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/etc/hyperledger/msp/tlscacerts/tls-ca-root-geodb-com-7500.pem
    volumes:
      - ../crypto-config/peerOrganizations/operations0.geodb.com:/etc/hyperledger/msp
      - ../crypto-config/peerOrganizations/operations0.geodb.com/peers/peer0.operations0.geodb.com/tls:/etc/hyperledger/tls
    depends_on:
      - peer0.operations0.geodb.com
    networks:
      - geodb

  clipeer1.operations0.geodb.com:
    extends:
      file: ../bases/cli-base.yaml
      service: cli
    container_name: clipeer1.operations0.geodb.com
    environment:
      - CORE_PEER_ID=clipeer1.operations0.geodb.com
      - CORE_PEER_ADDRESS=peer1.operations0.geodb.com:7151
      - CORE_PEER_LOCALMSPID=geodbMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@operations0.geodb.com/msp
      # - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/etc/hyperledger/msp/tlscacerts/tls-ca-root-geodb-com-7500.pem
    volumes:
      - ../crypto-config/peerOrganizations/operations0.geodb.com:/etc/hyperledger/msp
      - ../crypto-config/peerOrganizations/operations0.geodb.com/peers/peer1.operations0.geodb.com/tls:/etc/hyperledger/tls
    depends_on:
      - peer1.operations0.geodb.com
    networks:
      - geodb

  clipeer2.operations0.geodb.com:
    extends:
      file: ../bases/cli-base.yaml
      service: cli
    container_name: clipeer2.operations0.geodb.com
    environment:
      - CORE_PEER_ID=clipeer2.operations0.geodb.com
      - CORE_PEER_ADDRESS=peer2.operations0.geodb.com:7251
      - CORE_PEER_LOCALMSPID=geodbMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@operations0.geodb.com/msp
      # - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/etc/hyperledger/msp/tlscacerts/tls-ca-root-geodb-com-7500.pem
    volumes:
      - ../crypto-config/peerOrganizations/operations0.geodb.com:/etc/hyperledger/msp
      - ../crypto-config/peerOrganizations/operations0.geodb.com/peers/peer2.operations0.geodb.com/tls:/etc/hyperledger/tls
    depends_on:
      - peer2.operations0.geodb.com
    networks:
      - geodb

  clipeer3.operations0.geodb.com:
    extends:
      file: ../bases/cli-base.yaml
      service: cli
    container_name: clipeer3.operations0.geodb.com
    environment:
      - CORE_PEER_ID=clipeer3.operations0.geodb.com
      - CORE_PEER_ADDRESS=peer3.operations0.geodb.com:7351
      - CORE_PEER_LOCALMSPID=geodbMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@operations0.geodb.com/msp
      # - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/etc/hyperledger/msp/tlscacerts/tls-ca-root-geodb-com-7500.pem
    volumes:
      - ../crypto-config/peerOrganizations/operations0.geodb.com:/etc/hyperledger/msp
      - ../crypto-config/peerOrganizations/operations0.geodb.com/peers/peer3.operations0.geodb.com/tls:/etc/hyperledger/tls
    depends_on:
      - peer3.operations0.geodb.com
    networks:
      - geodb

  peer0.operations1.geodb.com:
    extends:
      file: ../bases/peer-base.yaml
      service: peer
    container_name: peer0.operations1.geodb.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=peer0.operations1.geodb.com
      - CORE_PEER_ADDRESS=peer0.operations1.geodb.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_LOCALMSPID=geodbMSP
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.operations1.geodb.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.operations1.geodb.com:7151 peer2.operations1.geodb.com:7251 peer3.operations1.geodb.com:7351
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/org1/peer0
    volumes:
      - /var/run:/host/var/run
      - ../crypto-config/peerOrganizations/operations1.geodb.com/peers/peer0.operations1.geodb.com:/etc/hyperledger/peer
    # ports:
    #   - 7051:7051
    #   - 7053:7053
    networks:
      - geodb

  peer1.operations1.geodb.com:
    extends:
      file: ../bases/peer-base.yaml
      service: peer
    container_name: peer1.operations1.geodb.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=peer1.operations1.geodb.com
      - CORE_PEER_ADDRESS=peer1.operations1.geodb.com:7151
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7151
      - CORE_PEER_LOCALMSPID=geodbMSP
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.operations1.geodb.com:7151
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.operations1.geodb.com:7051 peer2.operations1.geodb.com:7251 peer3.operations1.geodb.com:7351
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/org1/peer1
    volumes:
      - /var/run:/host/var/run
      - ../crypto-config/peerOrganizations/operations1.geodb.com/peers/peer1.operations1.geodb.com:/etc/hyperledger/peer
    # ports:
    #   - 7151:7151
    #   - 7153:7153
    networks:
      - geodb

  peer2.operations1.geodb.com:
    extends:
      file: ../bases/peer-base.yaml
      service: peer
    container_name: peer2.operations1.geodb.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=peer2.operations1.geodb.com
      - CORE_PEER_ADDRESS=peer2.operations1.geodb.com:7251
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7251
      - CORE_PEER_LOCALMSPID=geodbMSP
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.operations1.geodb.com:7251
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.operations1.geodb.com:7051 peer1.operations1.geodb.com:7151 peer3.operations1.geodb.com:7351
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/org1/peer2
    volumes:
      - /var/run:/host/var/run
      - ../crypto-config/peerOrganizations/operations1.geodb.com/peers/peer2.operations1.geodb.com:/etc/hyperledger/peer
    # ports:
    #   - 7051:7051
    #   - 7053:7053
    networks:
      - geodb 

  peer3.operations1.geodb.com:
    extends:
      file: ../bases/peer-base.yaml
      service: peer
    container_name: peer3.operations1.geodb.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=peer3.operations1.geodb.com
      - CORE_PEER_ADDRESS=peer3.operations1.geodb.com:7351
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7351
      - CORE_PEER_LOCALMSPID=geodbMSP
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer3.operations1.geodb.com:7351
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.operations1.geodb.com:7051 peer1.operations1.geodb.com:7151 peer2.operations1.geodb.com:7251
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/org1/peer2
    volumes:
      - /var/run:/host/var/run
      - ../crypto-config/peerOrganizations/operations1.geodb.com/peers/peer3.operations1.geodb.com:/etc/hyperledger/peer
    # ports:
    #   - 7051:7051
    #   - 7053:7053
    networks:
      - geodb

  clipeer0.operations1.geodb.com:
    extends:
      file: ../bases/cli-base.yaml
      service: cli
    container_name: clipeer0.operations1.geodb.com
    environment:
      - CORE_PEER_ID=clipeer0.operations1.geodb.com
      - CORE_PEER_ADDRESS=peer0.operations1.geodb.com:8051
      - CORE_PEER_LOCALMSPID=geodb2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@operations1.geodb.com/msp
      # - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/etc/hyperledger/tls/msp/tlscacerts/tls-ca-root-geodb-com-7500.pem
    volumes:
      - ../crypto-config/peerOrganizations/operations1.geodb.com:/etc/hyperledger/msp
      - ../crypto-config/peerOrganizations/operations1.geodb.com/peers/peer0.operations1.geodb.com/tls:/etc/hyperledger/tls
    depends_on:
      - peer0.operations1.geodb.com
    networks:
      - geodb

  clipeer1.operations1.geodb.com:
    extends:
      file: ../bases/cli-base.yaml
      service: cli
    container_name: clipeer1.operations1.geodb.com
    environment:
      - CORE_PEER_ID=clipeer1.operations1.geodb.com
      - CORE_PEER_ADDRESS=peer1.operations1.geodb.com:8151
      - CORE_PEER_LOCALMSPID=geodb2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@operations1.geodb.com/msp
      # - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/etc/hyperledger/tls/msp/tlscacerts/tls-ca-root-geodb-com-7500.pem
    volumes:
      - ../crypto-config/peerOrganizations/operations1.geodb.com:/etc/hyperledger/msp
      - ../crypto-config/peerOrganizations/operations1.geodb.com/peers/peer1.operations1.geodb.com/tls:/etc/hyperledger/tls
    depends_on:
      - peer1.operations1.geodb.com
    networks:
      - geodb

  clipeer2.operations1.geodb.com:
    extends:
      file: ../bases/cli-base.yaml
      service: cli
    container_name: clipeer2.operations1.geodb.com
    environment:
      - CORE_PEER_ID=clipeer2.operations1.geodb.com
      - CORE_PEER_ADDRESS=peer2.operations1.geodb.com:8251
      - CORE_PEER_LOCALMSPID=geodb2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@operations1.geodb.com/msp
      # - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/etc/hyperledger/tls/msp/tlscacerts/tls-ca-root-geodb-com-7500.pem
    volumes:
      - ../crypto-config/peerOrganizations/operations1.geodb.com:/etc/hyperledger/msp
      - ../crypto-config/peerOrganizations/operations1.geodb.com/peers/peer2.operations1.geodb.com/tls:/etc/hyperledger/tls
    depends_on:
      - peer2.operations1.geodb.com
    networks:
      - geodb

  clipeer3.operations1.geodb.com:
    extends:
      file: ../bases/cli-base.yaml
      service: cli
    container_name: clipeer3.operations1.geodb.com
    environment:
      - CORE_PEER_ID=clipeer3.operations1.geodb.com
      - CORE_PEER_ADDRESS=peer3.operations1.geodb.com:8351
      - CORE_PEER_LOCALMSPID=geodb2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@operations1.geodb.com/msp
      # - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/etc/hyperledger/tls/msp/tlscacerts/tls-ca-root-geodb-com-7500.pem
    volumes:
      - ../crypto-config/peerOrganizations/operations1.geodb.com:/etc/hyperledger/msp
      - ../crypto-config/peerOrganizations/operations1.geodb.com/peers/peer3.operations1.geodb.com/tls:/etc/hyperledger/tls
    depends_on:
      - peer3.operations1.geodb.com
    networks:
      - geodb

  couchdb:
    container_name: couchdb
    image: hyperledger/fabric-couchdb
    environment:
      DB_URL: http://localhost:5984/
    ports:
      - "5984:5984"
    networks:
      - geodb
