version: "2"

networks:
  geodb:

volumes:
        orderer1.orderer.geodb.com:
        orderer2.orderer.geodb.com:
        orderer3.orderer.geodb.com:
        orderer4.orderer.geodb.com:

services:
  orderer1.orderer.geodb.com:
    extends:
      file: ../bases/orderer-base.yaml
      service: orderer
    container_name: orderer1.orderer.geodb.com
    environment:
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0 
      - ORDERER_GENERAL_LISTENPORT=8050
    # extra_hosts:
    #         - "orderer0.orderer.geodb.com:34.68.86.73"
    #         - "orderer2.orderer.geodb.com:34.68.86.73"
    #         - "orderer3.orderer.geodb.com:34.68.86.73"
    #         - "orderer4.orderer.geodb.com:34.68.86.73"
    #         - "peer0.operations0.geodb.com:35.226.79.220"
    #         - "peer0.operations1.geodb.com:35.232.199.30"
    volumes:
      - ../orderer/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../crypto-config/ordererOrganizations/orderer.geodb.com/orderers/orderer1.orderer.geodb.com/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/orderer.geodb.com/orderers/orderer1.orderer.geodb.com/tls:/var/hyperledger/orderer/tls
      - ../channels/:/var/hyperledger/configs
      - orderer1.orderer.geodb.com:/var/hyperledger/production/orderer
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    ports:
      - 8050:7050
    networks:
      - geodb

  orderer2.orderer.geodb.com:
    extends:
      file: ../bases/orderer-base.yaml
      service: orderer
    container_name: orderer2.orderer.geodb.com
    environment:
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0 
      - ORDERER_GENERAL_LISTENPORT=9050
    # extra_hosts:
    #         - "orderer0.orderer.geodb.com:34.68.86.73"
    #         - "orderer1.orderer.geodb.com:34.68.86.73"
    #         - "orderer3.orderer.geodb.com:34.68.86.73"
    #         - "orderer4.orderer.geodb.com:34.68.86.73"
    #         - "peer0.operations0.geodb.com:35.226.79.220"
    #         - "peer0.operations1.geodb.com:35.232.199.30"
    volumes:
      - ../orderer/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../crypto-config/ordererOrganizations/orderer.geodb.com/orderers/orderer2.orderer.geodb.com/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/orderer.geodb.com/orderers/orderer2.orderer.geodb.com/tls:/var/hyperledger/orderer/tls
      - ../channels/:/var/hyperledger/configs
      - orderer2.orderer.geodb.com:/var/hyperledger/production/orderer
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    ports:
      - 9050:7050
    networks:
      - geodb

  orderer3.orderer.geodb.com:
    extends:
      file: ../bases/orderer-base.yaml
      service: orderer
    container_name: orderer3.orderer.geodb.com
    environment:
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0 
      - ORDERER_GENERAL_LISTENPORT=10050
    # extra_hosts:
    #         - "orderer0.orderer.geodb.com:34.68.86.73"
    #         - "orderer1.orderer.geodb.com:34.68.86.73"
    #         - "orderer2.orderer.geodb.com:34.68.86.73"
    #         - "orderer4.orderer.geodb.com:34.68.86.73"
    #         - "peer0.operations0.geodb.com:35.226.79.220"
    #         - "peer0.operations1.geodb.com:35.232.199.30"
    volumes:
      - ../orderer/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../crypto-config/ordererOrganizations/orderer.geodb.com/orderers/orderer3.orderer.geodb.com/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/orderer.geodb.com/orderers/orderer3.orderer.geodb.com/tls:/var/hyperledger/orderer/tls
      - ../channels/:/var/hyperledger/configs
      - orderer3.orderer.geodb.com:/var/hyperledger/production/orderer
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    ports:
      - 10050:7050
    networks:
      - geodb

  orderer4.orderer.geodb.com:
    extends:
      file: ../bases/orderer-base.yaml
      service: orderer
    container_name: orderer4.orderer.geodb.com
    environment:
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0 
      - ORDERER_GENERAL_LISTENPORT=11050
    # extra_hosts:
    #         - "orderer0.orderer.geodb.com:34.68.86.73"
    #         - "orderer1.orderer.geodb.com:34.68.86.73"
    #         - "orderer2.orderer.geodb.com:34.68.86.73"
    #         - "orderer3.orderer.geodb.com:34.68.86.73"
    #         - "peer0.operations0.geodb.com:35.226.79.220"
    #         - "peer0.operations1.geodb.com:35.232.199.30"
    volumes:
      - ../orderer/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../crypto-config/ordererOrganizations/orderer.geodb.com/orderers/orderer4.orderer.geodb.com/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/orderer.geodb.com/orderers/orderer4.orderer.geodb.com/tls:/var/hyperledger/orderer/tls
      - ../channels/:/var/hyperledger/configs
      - orderer4.orderer.geodb.com:/var/hyperledger/production/orderer
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    ports:
      - 11050:7050
    networks:
      - geodb

  # cli1.orderer.geodb.com:
  #   extends:
  #     file: ../bases/cli-base.yaml
  #     service: cli
  #   container_name: cli1.orderer.geodb.com
  #   environment:
  #     - CORE_PEER_ID=cli1.orderer.geodb.com
  #     - CORE_PEER_ADDRESS=orderer1.orderer.geodb.com:8050
  #     - CORE_PEER_LOCALMSPID=geodbMSP
  #     - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@orderer.geodb.com/msp
  #   # extra_hosts:
  #   #   - "orderer1.operations0.geodb.com:34.68.86.73"
  #   #   - "orderer2.operations0.geodb.com:34.68.86.73"
  #   #   - "orderer3.operations0.geodb.com:34.68.86.73"
  #   #   - "orderer4.operations0.geodb.com:34.68.86.73"
  #   #   - "peer0.operations0.geodb.com:35.226.79.220"
  #   #   - "peer0.operations1.geodb.com:35.232.199.30"
  #   volumes:
  #     - ../crypto-config/peerOrganizations/orderer.geodb.com:/etc/hyperledger/msp
  #     - /var/run/:/host/var/run/
  #     - ../chaincode/:/opt/gopath/src/github.com/chaincode
  #     - $GOPATH/src/github.com/hyperledger/fabric/:/opt/gopath/src/github.com/hyperledger/fabric/
  #     - ../crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
  #     - ../channels:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts/
  #   depends_on:
  #     - orderer1.orderer.geodb.com
  #   networks:
  #     - geodb

  # cli2.orderer.geodb.com:
  #   extends:
  #     file: ../bases/cli-base.yaml
  #     service: cli
  #   container_name: cli2.orderer.geodb.com
  #   environment:
  #     - CORE_PEER_ID=cli2.orderer.geodb.com
  #     - CORE_PEER_ADDRESS=orderer2.orderer.geodb.com:9050
  #     - CORE_PEER_LOCALMSPID=geodbMSP
  #     - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@orderer.geodb.com/msp
  #   # extra_hosts:
  #   #   - "orderer1.operations0.geodb.com:34.68.86.73"
  #   #   - "orderer2.operations0.geodb.com:34.68.86.73"
  #   #   - "orderer3.operations0.geodb.com:34.68.86.73"
  #   #   - "orderer4.operations0.geodb.com:34.68.86.73"
  #   #   - "peer0.operations0.geodb.com:35.226.79.220"
  #   #   - "peer0.operations1.geodb.com:35.232.199.30"
  #   volumes:
  #     - ../crypto-config/peerOrganizations/orderer.geodb.com:/etc/hyperledger/msp
  #     - /var/run/:/host/var/run/
  #     - ../chaincode/:/opt/gopath/src/github.com/chaincode
  #     - $GOPATH/src/github.com/hyperledger/fabric/:/opt/gopath/src/github.com/hyperledger/fabric/
  #     - ../crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
  #     - ../channels:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts/
  #   depends_on:
  #     - orderer2.orderer.geodb.com
  #   networks:
  #     - geodb
  
  # cli3.orderer.geodb.com:
  #   extends:
  #     file: ../bases/cli-base.yaml
  #     service: cli
  #   container_name: cli3.orderer.geodb.com
  #   environment:
  #     - CORE_PEER_ID=cli3.orderer.geodb.com
  #     - CORE_PEER_ADDRESS=orderer3.orderer.geodb.com:7050
  #     - CORE_PEER_LOCALMSPID=geodbMSP
  #     - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@orderer.geodb.com/msp
  #   # extra_hosts:
  #   #   - "orderer1.operations0.geodb.com:34.68.86.73"
  #   #   - "orderer2.operations0.geodb.com:34.68.86.73"
  #   #   - "orderer3.operations0.geodb.com:34.68.86.73"
  #   #   - "orderer4.operations0.geodb.com:34.68.86.73"
  #   #   - "peer0.operations0.geodb.com:35.226.79.220"
  #   #   - "peer0.operations1.geodb.com:35.232.199.30"
  #   volumes:
  #     - ../crypto-config/peerOrganizations/orderer.geodb.com:/etc/hyperledger/msp
  #     - /var/run/:/host/var/run/
  #     - ../chaincode/:/opt/gopath/src/github.com/chaincode
  #     - $GOPATH/src/github.com/hyperledger/fabric/:/opt/gopath/src/github.com/hyperledger/fabric/
  #     - ../crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
  #     - ../channels:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts/
  #   depends_on:
  #     - orderer3.orderer.geodb.com
  #   networks:
  #     - geodb

  # cli4.orderer.geodb.com:
  #   extends:
  #     file: ../bases/cli-base.yaml
  #     service: cli
  #   container_name: cli4.orderer.geodb.com
  #   environment:
  #     - CORE_PEER_ID=cli4.orderer.geodb.com
  #     - CORE_PEER_ADDRESS=orderer4.orderer.geodb.com:7050
  #     - CORE_PEER_LOCALMSPID=geodbMSP
  #     - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@orderer.geodb.com/msp
  #   # extra_hosts:
  #   #   - "orderer1.operations0.geodb.com:34.68.86.73"
  #   #   - "orderer2.operations0.geodb.com:34.68.86.73"
  #   #   - "orderer3.operations0.geodb.com:34.68.86.73"
  #   #   - "orderer4.operations0.geodb.com:34.68.86.73"
  #   #   - "peer0.operations0.geodb.com:35.226.79.220"
  #   #   - "peer0.operations1.geodb.com:35.232.199.30"
  #   volumes:
  #     - ../crypto-config/peerOrganizations/orderer.geodb.com:/etc/hyperledger/msp
  #     - /var/run/:/host/var/run/
  #     - ../chaincode/:/opt/gopath/src/github.com/chaincode
  #     - $GOPATH/src/github.com/hyperledger/fabric/:/opt/gopath/src/github.com/hyperledger/fabric/
  #     - ../crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
  #     - ../channels:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts/
  #   depends_on:
  #     - orderer4.orderer.geodb.com
  #   networks:
  #     - geodb