version: "2"

networks:
  geodb:

services:
  orderer0.operations.geodb.com:
    extends:
      file: ../bases/orderer-base.yaml
      service: orderer
    container_name: orderer0.operations.geodb.com
    environment:
      - ORDERER_GENERAL_LOCALMSPID=geodbMSP
    volumes:
      - ../crypto-config/operations.geodb.com/orderers/orderer0.operations.geodb.com/msp:/var/hyperledger/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    ports:
      - 7050:7050
    networks:
      - geodb
  
  orderer0.operations2.geodb.com:
    extends:
      file: ../bases/orderer-base.yaml
      service: orderer
    container_name: orderer0.operations2.geodb.com
    environment:
      - ORDERER_GENERAL_LOCALMSPID=geodbMSP2
    volumes:
      - ../crypto-config/operations2.geodb.com/orderers/orderer0.operations2.geodb.com/msp:/var/hyperledger/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    ports:
      - 7150:7150
    networks:
      - geodb

  peer0.operations.geodb.com:
    extends:
      file: ../bases/peer-base.yaml
      service: peer
    container_name: peer0.operations.geodb.com
    environment:
      - CORE_PEER_ID=peer0.operations.geodb.com
      - CORE_PEER_ADDRESS=peer0.operations.geodb.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_LOCALMSPID=geodbMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.operations.geodb.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.operations.example.com:7151
    volumes:
      - ../crypto-config/operations.geodb.com/peers/peer0.operations.geodb.com/msp:/etc/hyperledger/msp/peer
      # - ../crypto-config/peerOrganizations/operations.geodb.com/peers/peer.operations.geodb.com/msp:/etc/hyperledger/msp/peer
    ports:
      - 7051:7051
      - 7053:7053
    depends_on:
      - orderer0.operations.geodb.com
    networks:
      - geodb

  peer1.operations.geodb.com:
    extends:
      file: ../bases/peer-base.yaml
      service: peer
    container_name: peer1.operations.geodb.com
    environment:
      - CORE_PEER_ID=peer1.operations.geodb.com
      - CORE_PEER_ADDRESS=peer1.operations.geodb.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_LOCALMSPID=geodbMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.operations.geodb.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer2.operations.example.com:7151
    volumes:
      - ../crypto-config/operations.geodb.com/peers/peer1.operations.geodb.com/msp:/etc/hyperledger/msp/peer
      # - ../crypto-config/peerOrganizations/operations.geodb.com/peers/peer.operations.geodb.com/msp:/etc/hyperledger/msp/peer
    ports:
      - 10051:10051
      - 10053:10053
    depends_on:
      - orderer0.operations.geodb.com
    networks:
      - geodb

  peer2.operations.geodb.com:
    extends:
      file: ../bases/peer-base.yaml
      service: peer
    container_name: peer2.operations.geodb.com
    environment:
      - CORE_PEER_ID=peer2.operations.geodb.com
      - CORE_PEER_ADDRESS=peer2.operations.geodb.com:7251
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7251
      - CORE_PEER_LOCALMSPID=geodbMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.operations.geodb.com:7251
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer3.operations.example.com:7351
    volumes:
      - ../crypto-config/operations.geodb.com/peers/peer2.operations.geodb.com/msp:/etc/hyperledger/msp/peer
      # - ../crypto-config/peerOrganizations/operations.geodb.com/peers/peer.operations.geodb.com/msp:/etc/hyperledger/msp/peer
    ports:
      - 7251:7251
      - 7253:7253
    depends_on:
      - orderer0.operations.geodb.com
    networks:
      - geodb

  peer3.operations.geodb.com:
    extends:
      file: ../bases/peer-base.yaml
      service: peer
    container_name: peer3.operations.geodb.com
    environment:
      - CORE_PEER_ID=peer3.operations.geodb.com
      - CORE_PEER_ADDRESS=peer3.operations.geodb.com:7351
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7351
      - CORE_PEER_LOCALMSPID=geodbMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.operations.geodb.com:7351
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.operations.example.com:10051
    volumes:
      - ../crypto-config/operations.geodb.com/peers/peer3.operations.geodb.com/msp:/etc/hyperledger/msp/peer
      # - ../crypto-config/peerOrganizations/operations.geodb.com/peers/peer.operations.geodb.com/msp:/etc/hyperledger/msp/peer
    ports:
      - 7351:7351
      - 7353:7353
    depends_on:
      - orderer0.operations.geodb.com
    networks:
      - geodb

  clipeer0.operations.geodb.com:
    extends:
      file: ../bases/cli-base.yaml
      service: cli
    container_name: clipeer0.operations.geodb.com
    environment:
      - CORE_PEER_ID=clipeer0.operations.geodb.com
      - CORE_PEER_ADDRESS=peer0.operations.geodb.com:7051
      - CORE_PEER_LOCALMSPID=geodbMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@operations.geodb.com/msp
    volumes:
      - ../crypto-config/operations.geodb.com:/etc/hyperledger/msp
    depends_on:
      - peer0.operations.geodb.com
    networks:
      - geodb

  clipeer1.operations.geodb.com:
    extends:
      file: ../bases/cli-base.yaml
      service: cli
    container_name: clipeer1.operations.geodb.com
    environment:
      - CORE_PEER_ID=clipeer1.operations.geodb.com
      - CORE_PEER_ADDRESS=peer1.operations.geodb.com:10051
      - CORE_PEER_LOCALMSPID=geodbMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@operations.geodb.com/msp
    volumes:
      - ../crypto-config/operations.geodb.com:/etc/hyperledger/msp
    depends_on:
      - peer1.operations.geodb.com
    networks:
      - geodb

  clipeer2.operations.geodb.com:
    extends:
      file: ../bases/cli-base.yaml
      service: cli
    container_name: clipeer2.operations.geodb.com
    environment:
      - CORE_PEER_ID=clipeer2.operations.geodb.com
      - CORE_PEER_ADDRESS=peer2.operations.geodb.com:7251
      - CORE_PEER_LOCALMSPID=geodbMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@operations.geodb.com/msp
    volumes:
      - ../crypto-config/operations.geodb.com:/etc/hyperledger/msp
    depends_on:
      - peer2.operations.geodb.com
    networks:
      - geodb

  clipeer3.operations.geodb.com:
    extends:
      file: ../bases/cli-base.yaml
      service: cli
    container_name: clipeer3.operations.geodb.com
    environment:
      - CORE_PEER_ID=clipeer3.operations.geodb.com
      - CORE_PEER_ADDRESS=peer3.operations.geodb.com:7351
      - CORE_PEER_LOCALMSPID=geodbMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@operations.geodb.com/msp
    volumes:
      - ../crypto-config/operations.geodb.com:/etc/hyperledger/msp
    depends_on:
      - peer3.operations.geodb.com
    networks:
      - geodb

  peer0.operations2.geodb.com:
    extends:
      file: ../bases/peer-base.yaml
      service: peer
    container_name: peer0.operations2.geodb.com
    environment:
      - CORE_PEER_ID=peer0.operations2.geodb.com
      - CORE_PEER_ADDRESS=peer0.operations2.geodb.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_LOCALMSPID=geodbMSP2
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.operations2.geodb.com:8051
    volumes:
      - ../crypto-config/operations2.geodb.com/peers/peer0.operations2.geodb.com/msp:/etc/hyperledger/msp/peer
      # - ../crypto-config/peerOrganizations/operations.geodb.com/peers/peer.operations.geodb.com/msp:/etc/hyperledger/msp/peer
    ports:
      - 8051:8051
      - 8053:8053
    depends_on:
      - orderer0.operations2.geodb.com
    networks:
      - geodb

  peer1.operations2.geodb.com:
    extends:
      file: ../bases/peer-base.yaml
      service: peer
    container_name: peer1.operations2.geodb.com
    environment:
      - CORE_PEER_ID=peer1.operations2.geodb.com
      - CORE_PEER_ADDRESS=peer1.operations2.geodb.com:8151
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8151
      - CORE_PEER_LOCALMSPID=geodbMSP2
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.operations2.geodb.com:8151
    volumes:
      - ../crypto-config/operations2.geodb.com/peers/peer1.operations2.geodb.com/msp:/etc/hyperledger/msp/peer
      # - ../crypto-config/peerOrganizations/operations.geodb.com/peers/peer.operations.geodb.com/msp:/etc/hyperledger/msp/peer
    ports:
      - 8151:8151
      - 8153:8153
    depends_on:
      - orderer0.operations2.geodb.com
    networks:
      - geodb

  peer2.operations2.geodb.com:
    extends:
      file: ../bases/peer-base.yaml
      service: peer
    container_name: peer2.operations2.geodb.com
    environment:
      - CORE_PEER_ID=peer2.operations2.geodb.com
      - CORE_PEER_ADDRESS=peer2.operations2.geodb.com:8251
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8251
      - CORE_PEER_LOCALMSPID=geodbMSP2
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.operations2.geodb.com:8251
    volumes:
      - ../crypto-config/operations2.geodb.com/peers/peer2.operations2.geodb.com/msp:/etc/hyperledger/msp/peer
      # - ../crypto-config/peerOrganizations/operations.geodb.com/peers/peer.operations.geodb.com/msp:/etc/hyperledger/msp/peer
    ports:
      - 8251:8251
      - 8253:8253
    depends_on:
      - orderer0.operations2.geodb.com
    networks:
      - geodb

  peer3.operations2.geodb.com:
    extends:
      file: ../bases/peer-base.yaml
      service: peer
    container_name: peer3.operations2.geodb.com
    environment:
      - CORE_PEER_ID=peer3.operations2.geodb.com
      - CORE_PEER_ADDRESS=peer3.operations2.geodb.com:8351
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8351
      - CORE_PEER_LOCALMSPID=geodbMSP2
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.operations2.geodb.com:8351
    volumes:
      - ../crypto-config/operations2.geodb.com/peers/peer3.operations2.geodb.com/msp:/etc/hyperledger/msp/peer
      # - ../crypto-config/peerOrganizations/operations.geodb.com/peers/peer.operations.geodb.com/msp:/etc/hyperledger/msp/peer
    ports:
      - 8351:8351
      - 8353:8353
    depends_on:
      - orderer0.operations2.geodb.com
    networks:
      - geodb

  clipeer0.operations2.geodb.com:
    extends:
      file: ../bases/cli-base.yaml
      service: cli
    container_name: clipeer0.operations2.geodb.com
    environment:
      - CORE_PEER_ID=clipeer0.operations2.geodb.com
      - CORE_PEER_ADDRESS=peer0.operations2.geodb.com:8051
      - CORE_PEER_LOCALMSPID=geodbMSP2
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@operations2.geodb.com/msp
    volumes:
      - ../crypto-config/operations2.geodb.com:/etc/hyperledger/msp
    depends_on:
      - peer0.operations2.geodb.com
    networks:
      - geodb

  clipeer1.operations2.geodb.com:
    extends:
      file: ../bases/cli-base.yaml
      service: cli
    container_name: clipeer1.operations2.geodb.com
    environment:
      - CORE_PEER_ID=clipeer1.operations2.geodb.com
      - CORE_PEER_ADDRESS=peer1.operations2.geodb.com:8151
      - CORE_PEER_LOCALMSPID=geodbMSP2
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@operations2.geodb.com/msp
    volumes:
      - ../crypto-config/operations2.geodb.com:/etc/hyperledger/msp
    depends_on:
      - peer1.operations2.geodb.com
    networks:
      - geodb

  clipeer2.operations2.geodb.com:
    extends:
      file: ../bases/cli-base.yaml
      service: cli
    container_name: clipeer2.operations2.geodb.com
    environment:
      - CORE_PEER_ID=clipeer2.operations2.geodb.com
      - CORE_PEER_ADDRESS=peer2.operations2.geodb.com:8251
      - CORE_PEER_LOCALMSPID=geodbMSP2
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@operations2.geodb.com/msp
    volumes:
      - ../crypto-config/operations2.geodb.com:/etc/hyperledger/msp
    depends_on:
      - peer2.operations2.geodb.com
    networks:
      - geodb

  clipeer3.operations2.geodb.com:
    extends:
      file: ../bases/cli-base.yaml
      service: cli
    container_name: clipeer3.operations2.geodb.com
    environment:
      - CORE_PEER_ID=clipeer3.operations2.geodb.com
      - CORE_PEER_ADDRESS=peer3.operations2.geodb.com:8351
      - CORE_PEER_LOCALMSPID=geodbMSP2
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@operations2.geodb.com/msp
    volumes:
      - ../crypto-config/operations2.geodb.com:/etc/hyperledger/msp
    depends_on:
      - peer3.operations2.geodb.com
    networks:
      - geodb

  couchdb:
    container_name: couchdb
    image: hyperledger/fabric-couchdb
    environment:
      DB_URL: http://localhost:5984/
    ports:
      - "5984:5984"
    networks:
      - geodb
